config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
    controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products

  root 'store#index', as: 'store'

end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title Depot Application
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  body class= "controller.controller_name"

    // Header
    .row
      .top-bar
        .top-bar-left
          ul.menu
            li.menu-text
              = image_tag("logo.png")
            li
              a href="#" Home
            li
              a href="#" Questions
            li
              a href="#" News

    .row
      .large-3.columns
        #side
          #cart
            = render @cart
          - if session[:user_id]
            ul
              li
                = link_to 'Orders', orders_path
              li
                = link_to 'Products', products_path
              li
                = link_to 'Users', users_path
            = button_to 'Logout', logout_path, method: :delete
      .large-9.columns
        #main
          = yield